package com.bookit.bifrost.common.util;

public enum TargetType {

	USER_RETRIEVAL, USER_CREATION, GENERIC_ERROR, USER, EMPTY_JWT_CLAIMS, JWT_CREATION, JWT_CLAIM_PARSE, USER_REGISTERED, LOGIN, LOGOUT, USER_LOGGED_OUT, INVALID_TOKEN

}
